language: node_js
node_js:
  - 8
# linux dist
dist: trusty

cache:
    directories:
    - node_modules
    - client/node_modules

install:
  - npm install
  - npm run build

# npm start with no hang up and allowing using command line/wait for 3 seconds for server start
script:
  - npm run lint
  - nohup npm run start &
  - sleep 3
  - npm run test