language: node_js
node_js:
  - 8
# linux dist
dist: trusty

cache:
    directories:
    - node_modules
    - client/node_modules

install:
  - npm install
  - cd client && npm install
# npm start with no hang up and allowing using command line/wait for 3 seconds for server start
script:
  - npm run lint
  - cd client && npm run test